#!/bin/bash
set -eu

echo '--- :house_with_garden: Setting up the environment'
export TEST_ENV_VAR=$(openssl aes-256-cbc -d -a -in secret/test -pass file:/etc/build_pass)
exit_stat=$?
echo "exit_stat: " $exit_stat
echo
